name: daily-sast-report
run-name: Daily SAST report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  sast-report:
    name: Daily SAST report
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Orca Secrets Scan
        uses: orcasecurity/shiftleft-secrets-action@v1
        with:
          api_token: ${{ secrets.orca_security_api_token }}
          project_key: ${{ env.PROJECT_KEY }}
          # ignore_git_history_baseline: false
